CREATE TABLE `qmaesoc` (
   `soccod` varchar(13) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `socnom` varchar(40) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `socno2` varchar(40) NOT NULL DEFAULT '',
   `socdom` varchar(40) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `socloc` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `soctel` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `socema` varchar(50) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `soctdd` char(2) NOT NULL DEFAULT '',
   `socdni` varchar(15) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `socnac` date NOT NULL DEFAULT '0000-00-00',
   `soctra` varchar(40) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `so2tel` varchar(20) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `sococu` varchar(40) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `soctar` varchar(30) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `socing` date NOT NULL DEFAULT '0000-00-00',
   `socpto` char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `socsta` char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `socpun` int(6) NOT NULL DEFAULT '0',
   `socacu` int(6) NOT NULL DEFAULT '0',
   `so2pun` int(6) NOT NULL DEFAULT '0',
   `so2acu` int(6) NOT NULL DEFAULT '0',
   `soccin` char(40) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `cheque` char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
   `actualizado` int(11) DEFAULT '0',
   `apellido_paterno` varchar(120) CHARACTER SET latin1 DEFAULT NULL,
   `apellido_materno` varchar(120) CHARACTER SET latin1 DEFAULT NULL,
   `sexo` int(1) DEFAULT NULL,
   `celular` varchar(30) CHARACTER SET latin1 DEFAULT NULL,
   `departamento` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
   `provincia` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
   `distrito` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
   `cinestar_preferido` int(11) DEFAULT NULL,
   `domicilio` tinytext CHARACTER SET latin1,
   `nombre` varchar(120) CHARACTER SET latin1 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

alter table qmaesoc add primary key(soccod);
