version: "3.3"

services:
  webserver:
    container_name: 'cea_webserver'
    build:
      context: ./bin/webserver
    restart: 'always'
    ports:
      - ${HOST_MACHINE_UNSECURE_HOST_PORT}:80
      - ${HOST_MACHINE_SECURE_HOST_PORT}:443
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    networks:
      ceanet:
        ipv4_address: 10.1.0.100
  mysql:
    container_name: 'cea_mysql'
    build:
      context: "./bin/${DATABASE}"
    restart: 'always'
    ports:
      - ${HOST_MACHINE_MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
    networks:
      - ceanet
  phpmyadmin:
    container_name: 'cea_phpmyadmin'
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - ceanet
  redis:
    container_name: 'cea_redis'
    image: redis:6.0.9
    ports:
      - ${HOST_MACHINE_REDIS_PORT}:6379
    networks:
      - ceanet
networks:
  ceanet:
    driver: bridge
    name: custom_ceanet
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
